from dotenv import load_dotenv
import os
import requests
import joblib
import pandas as pd
import json
from jsonschema import validate, ValidationError
import re

# Load variables from .env
load_dotenv()

# Task 1: Set up the LLM API connection & LLM call resuable function
# API connection
api_key = os.getenv("OPENROUTER_API_KEY")

#OPENROUTER_API_BASE = "https://openrouter.ai/api/v1"
#OPENROUTER_MODEL    = "openai/gpt-oss-120b:free"

print("API key and OpenRouter settings loaded.")
if api_key:
   print(f"Key preview: {api_key[:8]}{'*' * 24}")
else:
   print("api_key not found. Add it under .env file.")

# Reusable LLM Function
 
def call_llm(system_prompt, user_prompt, temperature=0.0, max_tokens=512):

    url = "https://openrouter.ai/api/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "openai/gpt-4.1-mini",
        "messages": [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ],
        "temperature": temperature,
        "max_tokens": max_tokens
    }


    response = requests.post(
        url,
        headers=headers,
        json=payload
    )


    if response.status_code != 200:
        print("Error:", response.status_code)
        return None


    return response.json()["choices"][0]["message"]["content"]

# API Test

test_response = call_llm(
    "You are a helpful assistant.",
    "Reply with only the word: hello"
)

print(test_response)

# Task 2: Prompt design
# System Prompt

system_prompt = """
You are a medical prediction explanation assistant.

Your task is to explain machine learning predictions generated by a diabetes risk classifier.

Return ONLY valid JSON.

Do not provide medical diagnosis.
Do not invent patient information.
Use only the information provided.

The JSON output must contain exactly these fields:

{
    "prediction_label": "string",
    "confidence_level": "low|medium|high",
    "top_reason": "string",
    "second_reason": "string",
    "next_step": "string"
}

All fields must be scalar values.
"""

# User Prompt Template

def create_user_prompt(features, prediction, probability):

    user_prompt = f"""
Explain the diabetes prediction generated by the model.

Feature values:
{features}

Model predicted class:
{prediction}

Prediction probability:
{probability:.3f}

Return only JSON using this structure:

{{
    "prediction_label": "string",
    "confidence_level": "low|medium|high",
    "top_reason": "string",
    "second_reason": "string",
    "next_step": "string"
}}
"""

    return user_prompt

# Load saved pipeline
best_model = joblib.load("part3/best_model.pkl")

# Example feature vector
test_record = {

    "Pregnant": 3,
    "Diastolic_BP": 75,
    "Skin_Fold": 30,
    "Serum_Insulin": 180,
    "BMI": 32,
    "Diabetes_Pedigree": 0.6,
    "Age": 45,
    "Hospital_Fortis": 0,
    "Hospital_Gleneagals": 0,
    "Hospital_Kavery": 1,
    "Hospital_MMM": 0

}

def model_pred(test_record):

    X_new = pd.DataFrame([test_record])

    # Model prediction & probability
    prediction = best_model.predict(X_new)[0]

    probability = best_model.predict_proba(X_new)[0][1]

    return prediction, probability

prediction, probability = model_pred(test_record)

# Create user prompt
user_prompt = create_user_prompt(
    test_record,
    prediction,
    probability
)

print(f"user prompt\n", user_prompt)

# Call LLM
response = call_llm(
    system_prompt,
    user_prompt,
    temperature=0
)
print(f"\nLLM response:\n:", response)

# Temperature A/B comparison with 3 different sample records as inputs
test_records = [

    # Test Input 1: Higher risk profile
    {
        "Pregnant": 6,
        "Diastolic_BP": 85,
        "Skin_Fold": 35,
        "Serum_Insulin": 250,
        "BMI": 38,
        "Diabetes_Pedigree": 0.85,
        "Age": 55,
        "Hospital_Fortis": 0,
        "Hospital_Gleneagals": 0,
        "Hospital_Kavery": 1,
        "Hospital_MMM": 0
    },


    # Test Input 2: Lower risk profile
    {
        "Pregnant": 0,
        "Diastolic_BP": 65,
        "Skin_Fold": 20,
        "Serum_Insulin": 90,
        "BMI": 22,
        "Diabetes_Pedigree": 0.20,
        "Age": 25,
        "Hospital_Fortis": 1,
        "Hospital_Gleneagals": 0,
        "Hospital_Kavery": 0,
        "Hospital_MMM": 0
    },


    # Test Input 3: Moderate risk profile
    {
        "Pregnant": 2,
        "Diastolic_BP": 75,
        "Skin_Fold": 28,
        "Serum_Insulin": 150,
        "BMI": 30,
        "Diabetes_Pedigree": 0.50,
        "Age": 40,
        "Hospital_Fortis": 0,
        "Hospital_Gleneagals": 1,
        "Hospital_Kavery": 0,
        "Hospital_MMM": 0
    }

]

temperature_results = []

for record in test_records:
    prediction, probability = model_pred(record)
    user_prompt = create_user_prompt(
        record,
        prediction,
        probability
    )
    print(f"user prompt\n", user_prompt)

    # Temperature 0 response
    output_temp0 = call_llm(
        system_prompt,
        user_prompt,
        temperature=0
    )

    print(f"\n output_temp0\n", output_temp0)
    # Temperature 0.7 response
    output_temp07 = call_llm(
        system_prompt,
        user_prompt,
        temperature=0.7
    )
    print(f"\n output_temp07\n", output_temp07)

    temperature_results.append({

        "Input": record,

        "Output at temp=0": output_temp0,

        "Output at temp=0.7": output_temp07

    })

temperature_df = pd.DataFrame(temperature_results)
print(f"\n Results\n", temperature_df.head())
temperature_df.to_csv("part4/task2_result.csv", index=False)

#-------------------------------
# Task 3: Structured output handling

# Define JSON Schema
explanation_schema = {

    "type": "object",

    "properties": {

        "prediction_label": {
            "type": "string"
        },

        "confidence_level": {
            "type": "string"
        },

        "top_reason": {
            "type": "string"
        },

        "second_reason": {
            "type": "string"
        },

        "next_step": {
            "type": "string"
        }

    },

    "required": [

        "prediction_label",
        "confidence_level",
        "top_reason",
        "second_reason",
        "next_step"

    ]

}

# Validation function
def validate_llm_response(response):

    fallback = {

        "prediction_label": None,
        "confidence_level": None,
        "top_reason": None,
        "second_reason": None,
        "next_step": None

    }
    try:

        # Remove whitespace
        cleaned_response = response.strip()


        # Convert text to JSON
        json_response = json.loads(cleaned_response)


        # Validate schema
        validate(
            instance=json_response,
            schema=explanation_schema
        )


        return json_response, "PASS"
    except json.JSONDecodeError as e:

        print("JSON Error:", e)

        return fallback, "FAIL - Invalid JSON"
    except ValidationError as e:

        print("Schema Error:", e.message)

        return fallback, "FAIL - Schema Validation"
    
# Feature Encoder
def encode_record(features):

    df = pd.DataFrame([features])
    # Ensure column order matches training
    df = df[best_model.feature_names_in_]
    return df

results=[]

for i, features in enumerate(test_records, start=1):

    print("\n==============================")
    print("Test Input", i)
    print("==============================")

    # Encode input
    X_encoded = encode_record(features)

    # Prediction
    prediction = best_model.predict(X_encoded)[0]
    probability = best_model.predict_proba(X_encoded)[0][1]

    print("\nFeatures:")
    print(features)
    print("\nPredicted Class:", prediction)
    print("Probability:", round(probability,3))

    # User prompt
    user_prompt = f"""

Feature values:
{features}

Predicted class:
{prediction}

Prediction probability:
{probability:.3f}

Explain this prediction.

"""
    # LLM call
    llm_response = call_llm(
        system_prompt,
        user_prompt,
        temperature=0
    )

    print("\nRaw LLM Response:")
    print(llm_response)

    # Validate output
    explanation, status = validate_llm_response(
        llm_response
    )

    print("\nValidation Status:", status)
    results.append({
        "Feature Input":features,
        "Predicted Class":prediction,
        "Probability":round(probability,3),
        "Explanation JSON":explanation,
        "Validation Status":status
    })

results_df = pd.DataFrame(results)
print(f"\n Results\n", temperature_df.head())
temperature_df.to_csv("part4/task3_result.csv", index=False)

# Task 4: Guardrail
# PII Guardrail Function

def has_pii(text):
    """
    Detects common personally identifiable information (PII)
    such as email addresses and phone numbers.
    """

    email_pattern = r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'

    phone_pattern = (
        r'\b\d{10}\b|'                 # 1234567890
        r'\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b'  # 123-456-7890
    )

    return bool(
        re.search(email_pattern, text) or
        re.search(phone_pattern, text)
    )

# Safe LLM Wrapper with PII Protection

def safe_call_llm(system_prompt, user_prompt, temperature=0.0, max_tokens=512):

    # Check for PII before sending data to LLM
    if has_pii(user_prompt):

        print("Input blocked: PII detected.")
        return None

    # If no PII detected, proceed with LLM call
    response = call_llm(
        system_prompt,
        user_prompt,
        temperature,
        max_tokens
    )

    return response

system_prompt1 = """
You are a medical prediction explanation assistant.
Return only valid JSON.
"""

pii_test_input = """
Patient information:
Name: John Smith
Email: john.smith@gmail.com

Explain this prediction.
"""

response = safe_call_llm(
    system_prompt1,
    pii_test_input
)

print(response)

clean_test_input = """
Patient features:
Age: 45
BMI: 31.2
Glucose: 145
Prediction Class: 1
Prediction Probability: 0.82

Provide a structured explanation.
"""

response = safe_call_llm(
    system_prompt1,
    clean_test_input
)

print(f"\n Task4-Guardrail-Result\n", response)

# Task 5: Demonstrate the feature end-to-end
# Three Test Feature Inputs

test_inputs = [

    {
        "Pregnant": 1,
        "Glucose": 120,
        "Diastolic_BP": 70,
        "Skin_Fold": 20,
        "Serum_Insulin": 85,
        "BMI": 25.5,
        "Diabetes_Pedigree": 0.35,
        "Age": 35,
        "Hospital_Fortis": 1,
        "Hospital_Gleneagals": 0,
        "Hospital_Kavery": 0,
        "Hospital_MMM": 0
    },


    {
        "Pregnant": 5,
        "Glucose": 160,
        "Diastolic_BP": 90,
        "Skin_Fold": 35,
        "Serum_Insulin": 200,
        "BMI": 34.2,
        "Diabetes_Pedigree": 0.75,
        "Age": 55,
        "Hospital_Fortis": 0,
        "Hospital_Gleneagals": 1,
        "Hospital_Kavery": 0,
        "Hospital_MMM": 0
    },


    {
        "Pregnant": 2,
        "Glucose": 105,
        "Diastolic_BP": 65,
        "Skin_Fold": 18,
        "Serum_Insulin": 70,
        "BMI": 23.8,
        "Diabetes_Pedigree": 0.20,
        "Age": 28,
        "Hospital_Fortis": 0,
        "Hospital_Gleneagals": 0,
        "Hospital_Kavery": 1,
        "Hospital_MMM": 0
    }

]



# -------------------------------------------------------
# Run Complete Pipeline
# -------------------------------------------------------

results = []


for i, features in enumerate(test_inputs, start=1):

    print("\n====================================")
    print(f"INPUT {i}")
    print("====================================")

    print(features)


    # Encode features
    X_new = encode_record(features)


    # Prediction
    prediction = best_model.predict(X_new)[0]

    probability = best_model.predict_proba(X_new)[0][1]


    print("\nModel Prediction:")
    print("Class:", prediction)
    print("Probability:", round(probability,4))


    # Create LLM user prompt

    user_prompt = f"""
Feature values:

{json.dumps(features, indent=2)}

Model prediction:
Class = {prediction}

Probability = {probability:.4f}

Explain this prediction.
Return JSON only.
"""


    # PII protected LLM call

    llm_response = safe_call_llm(
        system_prompt,
        user_prompt,
        temperature=0
    )


    print("\nRaw LLM Response:")
    print(llm_response)

    response = llm_response.strip()

    # Remove Markdown code block if present
    if response.startswith("```"):
        response = response.replace("```json", "")
        response = response.replace("```", "")
        response = response.strip()

    # Parse JSON
    try:
        parsed_json = json.loads(response)

        validate(
            instance=parsed_json,
            schema=explanation_schema
        )

        validation_status = "PASS"

    except json.JSONDecodeError as e:
        print("JSON Parsing Error:", e)

    except ValidationError as e:
        print("Schema Validation Error:", e)
        print("\nValidation Result:")
        print(validation_status)

    results.append({
        "Input": features,
        "Prediction": prediction,
        "Probability": round(probability,4),
        "LLM Output": parsed_json if validation_status=="PASS" else None,
        "Validation": validation_status
    })

results_df = pd.DataFrame(results)
print(f"\n Results-final\n", results_df.head())
results_df.to_csv("part4/task5_result.csv", index=False)